version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: lint
          command: make shellcheck
      - run:
          name: unnamed
          command: make unnamed
      - run:
          name: service
          command: make consumer
      - run:
          name: dind
          command: make dind
      - run:
          name: brainfuck
          command: make brainfuck
